version: "3"
services:
    php:
        build: "./php"
        container_name: "php"
        # expose:
        #     - 9000
        volumes:
            - "./html:/var/www/html"
        #working_dir: "/usr/share/code"
        environment:
            - "TZ=Asia/Bangkok"
        networks:
            - ppshrms-network
        restart: always
    backend:
        build: "./nginx"
        container_name: "nginx"
        environment:
            - TZ=Asia/Bangkok
        volumes:
            - "./html:/var/www/html"
            - "./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro"
            - "./nginx/conf.d:/etc/nginx/conf.d:ro"
        ports:
            - 8080:80
        links:
            - php    
        networks:
            - ppshrms-network
        restart: always
networks:
  ppshrms-network:
    driver: bridge
