name: Docker Image CI

on:
  push:
    branches: [ "alpha2" ]
  pull_request:
    branches: [ "alpha2" ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: PHP Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./php
          push: true
          tags: peopleplus/nginx-php-oci8-19c-beta:latest
 
